version: "3"

services:
  contagion-updater:
    build:
      context: .
    image: ct-contagion-updater:latest
    container_name: 'contagion-updater'
    environment:
      - QUEUE_ADDRESS=amqp://guest:guest@codes-queue:5672/
      - QUEUE_NAME=infected-codes
      - MONGODB_URI=mongodb://ct-contagion-updater-db:27017/ct-contagion-updater-db
    depends_on:
      - codes-queue
    networks:
      - queue-network

  ct-contagion-updater-db:
    image: mongo:3.6.4

  codes-queue:
    image: rabbitmq:3-management-alpine
    container_name: 'codes-queue'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq-info/data/:/var/lib/rabbitmq/
        - ./rabbitmq-info/log/:/var/log/rabbitmq
    networks:
        - queue-network

networks:
  queue-network:

  